--------------------------------------------------------
--  File created - Sunday-March-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table JC_SCANDATA_ALT_SHIP_VIA
--------------------------------------------------------

  CREATE TABLE "WMSOPS"."JC_SCANDATA_ALT_SHIP_VIA" 
   (	"JC_SCANDATA_ALT_SHIP_VIA_ID" NUMBER(6,0), 
	"SHIP_VIA" VARCHAR2(4 BYTE), 
	"SITE" VARCHAR2(2 BYTE), 
	"CARRIER_CODE" VARCHAR2(8 BYTE), 
	"ALT_SHIP_VIA" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBO_BASE_DT_TBS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00426298
--------------------------------------------------------

  CREATE UNIQUE INDEX "WMSOPS"."SYS_C00426298" ON "WMSOPS"."JC_SCANDATA_ALT_SHIP_VIA" ("JC_SCANDATA_ALT_SHIP_VIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBO_BASE_DT_TBS" ;
--------------------------------------------------------
--  DDL for Index JC_SCANDATA_ALT_SHIP_VIA_IDX1
--------------------------------------------------------

  CREATE INDEX "WMSOPS"."JC_SCANDATA_ALT_SHIP_VIA_IDX1" ON "WMSOPS"."JC_SCANDATA_ALT_SHIP_VIA" ("SHIP_VIA", "SITE", "CARRIER_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBO_BASE_DT_TBS" ;
--------------------------------------------------------
--  Constraints for Table JC_SCANDATA_ALT_SHIP_VIA
--------------------------------------------------------

  ALTER TABLE "WMSOPS"."JC_SCANDATA_ALT_SHIP_VIA" ADD PRIMARY KEY ("JC_SCANDATA_ALT_SHIP_VIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBO_BASE_DT_TBS"  ENABLE;
